---
- name: correr script
  hosts: all
  become: yes
  tasks:
    - name: crear carpeta de scripts
      file:
        path: /home/user/scripts
        state: directory

    - name: copiar el script
      synchronize:
        src: /tmp/bmcagentinstall.sh
        dest: /tmp/bmcagentinstall.sh
        mode: pull
      delegate_to: ANS-M01

    - name: ejecutar script como sudo
      command: bash tmp/bmcagentinstall.sh
      register: console

    - debug: msg="{{ console.stdout }}"

    - debug: msg="{{ console.stderr }}" 
