---
- name: correr script
  hosts: all
  become: yes
  tasks:
    - name: copiar el script
      copy:
        src: /tmp/bmcagentinstall.sh
        dest: /tmp/bmcagentinstall.sh
        remote_src: yes

    - name: ejecutar script como sudo
      command: bash tmp/bmcagentinstall.sh
      register: console

    - debug: msg="{{ console.stdout }}"

    - debug: msg="{{ console.stderr }}" 
