---
 - name: Copy a new "sudoers" file into place, after passing validation with visudo
   hosts: all
   ansible.builtin.copy:
     src: /tmp/bmcagentinstall.sh/
     remote_src: yes
     dest: /tmp/