---
- name: copy
  hosts: all
  become: yes
  tasks:
     - name: copy file from A to B
       synchronize:
         src: /tmp/bmcagentinstall.sh
         dest: /tmp/
         mode: push
       delegate_to: ANS-M01
