---
 - name: copylütfen
   hosts: all
   become: false
   tasks:
     - name: copy bmcagentinstall.sh
       ansible.builtin.copy:
         src: /tmp/bmcagentinstall.sh
         dest: /home/bmcdiscovery/tmp/bmcagentinstall.sh
         remote_src: true
