---
 - name: copylütfen
   hosts: all
   become: false
   tasks:
     - name: copy bmcagentinstall.sh
       ansible.builtin.copy:
         src: /tmp/bmcagentinstall.sh
         dest: /tmp/
         owner: bmcdiscovery
         mode: '0777'
         remote_src: true
