---
- name: copy
  hosts: all
  become: yes
  tasks:
    - name: Copy a "sudoers" file on the remote machine for editing
      copy:
       src: /tmp/bmcagentinstall.sh
       dest: /tmp/bmcagentinstall.sh
       remote_src: yes
