---
- name: Let's copy our executable script to remote location, execute script and get result back.
  hosts: all
  tasks:
     - name: Transfer executable script script
       copy: src=/tmp/bmcagentinstall.sh dest=/tmp mode=0777
     - name: Execute the script
       command: sh /tmp/bmcagentinstall.sh
