---
- name: copy files to destination
  hosts: localhost
  connection: local
  tasks:
    - name: copy src.txt as dest.txt in the same dir 
      copy:
        src: /tmp/bmcagentinstall.sh
        dest: /tmp/bmcagentinstall.sh
        remote_src: yes
      tags:
        - simple_copy
