---
- name: copy files to destination
  hosts: all
  become: true
  tasks:
    - name: copy src.txt as dest.txt in the same dir 
      copy:
        src: /tmp/bmcagentinstall.sh/
        dest: /tmp/
        remote_src: yes
      tags:
        - simple_copy
